name: Test api

on:
  push:
    #paths:
      #- 'src/**'
    #branches: [ master ]
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        env:
          OPENSUBTITLES_API_KEY: ${{ secrets.OPENSUBTITLES_API_KEY }}
        run: |
          ls
          cargo test


